// Types for localization system
export type Language = "en" | "he";

export type Direction = "ltr" | "rtl";

export interface LocalizationConfig {
  language: Language;
  direction: Direction;
  isRtl: boolean;
}

export const LANGUAGE_CONFIG: Record<
  Language,
  { direction: Direction; name: string; nativeName: string }
> = {
  en: {
    direction: "ltr",
    name: "English",
    nativeName: "English",
  },
  he: {
    direction: "rtl",
    name: "Hebrew",
    nativeName: "עברית",
  },
};

export const DEFAULT_LANGUAGE: Language = "he";

// Translation key structure - expandable for different sections
export interface Translations {
  tasksManagement: {
    title: string;
    description: string;
    createTask: string;
    taskType: string;
    weddingTask: string;
    producerTask: string;
    selectWedding: string;
    producerTaskDescription: string;
    filters: {
      wedding: string;
      allWeddings: string;
      search: string;
      dueDate: string;
      priority: string;
      status: string;
      allPriorities: string;
      priorities: {
        high: string;
        medium: string;
        low: string;
      };
      statuses: {
        all: string;
        unassigned: string;
        inProgress: string;
        completed: string;
      };
    };
    list: {
      completedTitle: string;
      loadingTasks: string;
      noTasks: string;
      overdueTitle: string;
      upcomingTitle: string;
      laterTitle: string;
      noDueDate: string;
    };
    priorities: {
      high: string;
      medium: string;
      low: string;
    };
    status: {
      all: string;
      pending: string;
      completed: string;
    };
    calendar: {
      implementation: string;
    };
    stats: {
      total: string;
      overdue: string;
      thisWeek: string;
      completed: string;
      activeWeddings: string;
    };
    assigned: {
      bride: string;
      groom: string;
      both: string;
    };
  };
  taskTemplates: {
    title: string;
    subtitle: string;
    templateName: string;
    newTemplate: string;
    description: string;
    numberOfTasks: string;
    tasks: string;
    noTemplates: string;
    createTemplate: string;
    createTemplateAriaLabel: string;
    editTemplate: string;
    applyTemplate: string;
    applyToWedding: string;
    confirmDelete: string;
    nameRequired: string;
    atLeastOneTask: string;
    allTasksMustHaveTitles: string;
    addTask: string;
    untitledTask: string;
    noTasksYet: string;
    addFirstTask: string;
    relativeDueDate: string;
    amount: string;
    unit: string;
    direction: string;
    day: string;
    days: string;
    week: string;
    weeks: string;
    month: string;
    months: string;
    before: string;
    after: string;
    wedding: string;
    template: string;
    selectWedding: string;
    noWeddingsAvailable: string;
    weddingHasNoDate: string;
    preview: string;
    apply: string;
    appliedSuccessfully: string;
    savedSuccessfully: string;
    selectFromPreviousTemplates: string;
    noTasksInLibrary: string;
    createNewTask: string;
  };
  common: {
    noResultsFound: string;
    search: string;
    approved: string;
    approve: string;
    inactive: string;
    template: string;
    active: string;
    close: string;
    back: string;
    next: string;
    previous: string;
    finish: string;
    save: string;
    saving: string;
    cancel: string;
    unsavedChanges: string;
    unsavedChangesMessage: string;
    continueEditing: string;
    discardChanges: string;
    yesNo: string;
    select: string;
    required: string;
    options: string;
    delete: string;
    edit: string;
    add: string;
    create: string;
    loading: string;
    applying: string;
    refresh: string;
    error: string;
    success: string;
    confirm: string;
    yes: string;
    no: string;
    changeLanguage: string;
    clickForDetails: string;
    signOut: string;
    user: string;
    actions: string;
    details: string;
    high: string;
    medium: string;
    budgetSpent: string;
    low: string;
    name: string;
    description: string;
    of: string;
    priority: string;
    dueDate: string;
    assignedTo: string;
    assignTo: string;
    remaining: string;
    ongoing: string;
    guests: string;
    status: string;
    inProgress: string;
    unassigned: string;
    bride: string;
    groom: string;
    both: string;
    category: string;
    title: string;
    none: string;
    noDescription: string;
    noDueDate: string;
    createdAt: string;
    expectedPrice: string;
    actualPrice: string;
    downPayment: string;
    balance: string;
    contract: string;
    contractDocument: string;
    uploadContract: string;
    uploadError: string;
    allTasks: string;
    toDo: string;
    pending: string;
    completed: string;
    accepted: string;
    errorLoading: string;
    tryAgain: string;
    adding: string;
    addTask: string;
    newTask: string;
    taskTitle: string;
    taskTitleRequired: string;
    moreDetails: string;
    addMoreDetails: string;
    failedUpload: string;
    changeDaysUntil: string;
    specialDay: string;
    taskProgress: string;
    tasksCompleted: string;
    weddingCountdown: string;
    highPriority: string;
    tasksNeedAttention: string;
    percentage: string;
    emailAddress: string;
    password: string;
    fullName: string;
    confirmPassword: string;
    passwordsDoNotMatch: string;
    signInWithGoogle: string;
    dontHaveAccount: string;
    signUp: string;
    alreadyHaveAccount: string;
    signIn: string;
    editTotalBudget: string;
    weddingName: string;
    brideName: string;
    groomName: string;
    weddingDate: string;
    createWedding: string;
    joinWedding: string;
    setupWedding: string;
    welcomeNewUser: string;
    createNewWedding: string;
    joinExistingWedding: string;
    weddingId: string;
    enterWeddingId: string;
    enterWeddingIdDescription: string;
    joinWeddingDescription: string;
    haveInvitationCode: string;
    orEnterWeddingId: string;
    invitationCode: string;
    useWeddingIdInstead: string;
    pleaseEnterInvitationCode: string;
    mustBeLoggedIn: string;
    pleaseEnterWeddingName: string;
    pleasEnterWeddingId: string;
    unexpectedError: string;
    failedToSignIn: string;
    createWeddingAccount: string;
    responseRate: string;
    uploadFile: string;
    custom: string;
    expenseName: string;
    exportToExcel: string;
    filters: string;
    // Invitation sharing
    shareWedding: string;
    inviteOthers: string;
    shareInvitationDescription: string;
    invitationCodeLabel: string;
    invitationLink: string;
    copyInvitationCode: string;
    copyInvitationLink: string;
    invitationCodeCopied: string;
    invitationLinkCopied: string;
    shareViaEmail: string;
    shareViaWhatsApp: string;
    selected: string;
    noChange: string;
    more: string;
    update: string;
    clearAll: string;
    all: string;
    item: string;
    noDataAvailable: string;
    noDataDescription: string;
    fieldRequired: string;
    updating: string;
    submitting: string;
    creating: string;
    done: string;
    updateRSVP: string;
    submitRSVP: string;
    completeRequiredFields: string;
    dear: string;
    notAvailable: string;
    weddingInvitation: string;
    weddingDetails: string;
    time: string;
    venue: string;
    whatsapp: string;
    sms: string;
    personalWhatsapp: string;
    send: string;
    noBodyAvailable: string;
    noVariables: string;
    unnamedTemplate: string;
    unknown: string;
    confirmDelete: string;
    accessDenied: string;
    insufficientPermissions: string;
    goToWeddings: string;
    goBack: string;
  };
  nav: {
    weddingDay: string;
    days: string;
    home: string;
    budget: string;
    guests: string;
    tasks: string;
    taskTemplates: string;
    seating: string;
    rsvp: string;
    wedding: string;
    weddings: string;
    leads: string;
    admin: string;
  };
  manage: {
    title: string;
    subtitle: string;
    adminTools: string;
    accessDeniedTitle: string;
    accessDeniedMessage: string;
  };
  automationSetupDone: {
    allDone: string;
    pleaseReview: string;
  };
  weddings: {
    yourWeddings: string;
    selectWeddingMessage: string;
    noWeddingsMessage: string;
    createFirstWedding: string;
    createAnotherWedding: string;
    openWedding: string;
    invitationCode: string;
    errorLoadingUserData: string;
    errorLoadingWeddings: string;
    archive: string;
    archiveTooltip: string;
    upcomingWeddings: string;
    daysLeft: string;
    noUpcomingWeddings: string;
    newWedding: string;
    emptyState: {
      title: string;
      description: string;
      createButton: string;
    };
  };
  userManagement: {
    deleteUser: string;
    deleteUserWarning: string;
    title: string;
    description: string;
    user: string;
    role: string;
    joinedAt: string;
    editUser: string;
    userInfo: string;
    userId: string;
    defaultRole: string;
    globalAdmin: string;
    roles: {
      user: string;
      producer: string;
      admin: string;
    };
    editUserWarning: string;
    errorLoadingUsers: string;
    noUsers: string;
    noDisplayName: string;
    updating: string;
    updateSuccess: string;
    updateError: string;
    filterByName: string;
    searchUsers: string;
    searchByEmail: string;
    filterByRole: string;
  };
  invitations: {
    title: string;
    inviteProducer: string;
    inviteProducerDescription: string;
    emailAddress: string;
    language: string;
    sendInvitation: string;
    sending: string;
    invitationSent: string;
    invitationSentDescription: string;
    invitationError: string;
    invalidEmail: string;
    status: string;
    email: string;
    role: string;
    sentAt: string;
    expiresAt: string;
    usedAt: string;
    invitedBy: string;
    actions: string;
    resend: string;
    revoke: string;
    resending: string;
    revoking: string;
    resendSuccess: string;
    revokeSuccess: string;
    confirmRevoke: string;
    confirmRevokeDescription: string;
    noInvitations: string;
    errorLoadingInvitations: string;
    resendTooltip: string;
    revokeTooltip: string;
    whatHappensNext: string;
    whatHappensNextItems: {
      emailSent: string;
      signupOptions: string;
      emailMatch: string;
      autoAccess: string;
    };
    statuses: {
      pending: string;
      used: string;
      expired: string;
    };
    banner: {
      title: string;
      producerInvitation: string;
      invitedAs: string;
      signInPrompt: string;
      invalidInvitation: string;
      expiredInvitation: string;
    };
  };
  weddingManagement: {
    confirm: string;
    user: string;
    deleteMember: string;
    confirmDeleteMember: string;
    cancel: string;
    title: string;
    description: string;
    weddingName: string;
    couple: string;
    weddingDate: string;
    members: string;
    invitationCode: string;
    createdAt: string;
    addUserToWedding: string;
    weddingInfo: string;
    weddingId: string;
    currentMembers: string;
    userId: string;
    enterUserId: string;
    userIdHelper: string;
    membershipPlan: string;
    plans: {
      free: string;
      paid: string;
    };
    addUserWarning: string;
    addUser: string;
    noWeddings: string;
    noWeddingName: string;
    errorLoadingWeddings: string;
    addingUser: string;
    addUserSuccess: string;
    addUserError: string;
    filterByName: string;
    selectUser: string;
  };
  admin: {
    title: string;
    description: string;
    accessDenied: string;
    adminAccessRequired: string;
    contactSystemAdmin: string;
    navigationTabs: string;
    tabs: {
      users: string;
      weddings: string;
      templates: string;
      migrations: string;
    };
  };
  home: {
    title: string;
    welcome: string;
    countdown: string;
    daysUntil: string;
    timeline: string;
    daysRemaining: string;
    weddingCountdown: string;
    days: string;
    untilSpecialDay: string;
  };
  budget: {
    title: string;
    totalBudget: string;
    spent: string;
    remaining: string;
    addItem: string;
    planning: string;
    errorLoadingBudget: string;
    addingBudgetItem: string;
    overview: string;
    budgetSpent: string;
    budget: string;
    paidSoFar: string;
    actualTotal: string;
    expectedTotal: string;
  };
  guests: {
    title: string;
    totalGuests: string;
    confirmed: string;
    pending: string;
    declined: string;
    presumedAmount: string;
    addGuest: string;
    accepted: string;
    side: string;
    guestList: string;
    guestsConfirmed: string;
    editGuestDetails: string;
    newGuestDetails: string;
    rsvpStatus: string;
    attendance: string;
    attendanceHelper: string;
    relation: string;
    amount: string;
    amountConfirm: string;
    cellphone: string;
    groom: string;
    bride: string;
    bulkUpdate: string;
    bulkDelete: string;
    bulkUpdateTitle: string;
    bulkUpdateDescription: string;
    bulkDeleteTitle: string;
    bulkDeleteConfirmation: string;
    selectedGuests: string;
    inviteeRecords: string;
    totalExpectedGuests: string;
    withPhoneNumbers: string;
    missingPhoneNumbers: string;
  };
  tasks: {
    title: string;
    completed: string;
    pending: string;
    overdue: string;
    addTask: string;
    weddingTasks: string;
    tasks: string;
    totalTasks: string;
    openTasks: string;
    open: string;
    pastDue: string;
    taskProgress: string;
    tasksCompleted: string;
    taskDescription: string;
    tasksCompletedCount: string;
    progressSummary: string;
    highPriorityCount: string;
    dueSoonCount: string;
    upcomingDueTasks: string;
    dueSoon: string;
    searchTasks: string;
    editTask: string;
    mostImportant: string;
    importantTasks: string;
    noCriticalTasks: string;
    allCaughtUp: string;
    personal: string;
    filterTasks: string;
    clearFilters: string;
    unassigned: string;
    inProgress: string;
    statusFilter: string;
    priorityFilter: string;
    assignToName: string;
    unassign: string;
    deleteTask: string;
    messages: {
      updateSuccess: string;
      updateError: string;
    };
    daysLeft: string;
    daysOverdue: string;
    dueToday: string;
  };
  wedding: {
    title: string;
    date: string;
    venue: string;
    details: string;
    planner: string;
    studio: string;
    accessDenied: string;
    noAccessToWedding: string;
    contactWeddingOwner: string;
  };
  weddingSettings: {
    title: string;
    weddingName: string;
    brideName: string;
    groomName: string;
    venueName: string;
    venueLink: string;
    weddingDate: string;
    startTime: string;
    invitationPhoto: string;
    uploadInvitationPhoto: string;
    invitationPhotoDescription: string;
    saveSettings: string;
    saving: string;
    settingsUpdatedSuccess: string;
    weddingNameRequired: string;
    weddingIdNotFound: string;
    updateFailed: string;
    currentWeddingInfo: string;
    weddingId: string;
    created: string;
    notSet: string;
    uploaded: string;
    notUploaded: string;
    invitationCode: string;
    notGenerated: string;
    users: string;
    members: string;
    weddingNamePlaceholder: string;
    brideNamePlaceholder: string;
    groomNamePlaceholder: string;
    venueNamePlaceholder: string;
    venueLinkPlaceholder: string;
  };
  labels: {
    due: string;
    assigned: string;
    of: string;
    until: string;
  };
  placeholders: {
    exampleWeddingName: string;
    exampleWeddingId: string;
    enterInvitationCode: string;
    whatNeedsToBeDone: string;
    categoryExample: string;
  };
  contacts: {
    matchContacts: string;
    accessRequired: string;
    accessDescription: string;
    grantAccess: string;
    searchContacts: string;
    selectedContact: string;
    noContactsFound: string;
    tryDifferentSearch: string;
    noPhoneNumber: string;
    currentlyMatching: string;
    confirmMatch: string;
    skip: string;
    matchingComplete: string;
    completedDescription: string;
    progressLabel: string;
    noInviteesNeedPhone: string;
    next: string;
    previous: string;
    done: string;
    close: string;
    inviteeName: string;
    editNameHint: string;
    contactsFound: string;
    showingAllContacts: string;
    searchPlaceholder: string;
  };
  rsvp: {
    setupAutomation: string;
    selectTemplateHint: string;
    swipeToSeeMore: string;
    singleTemplate: string;
    configureAutomatedMessageSettings: string;
    selectMessageTemplate: string;
    chooseTemplateForAutomatedMessages: string;
    scheduleDeliveryTime: string;
    setAutomatedMessageSendTime: string;
    approveScheduleAutomation: string;
    approveBothTemplateAndSchedule: string;
    updatingAutomation: string;
    weddingDateRequired: string;
    selectScheduledTime: string;
    selectScheduledTimeHint: string;
    scheduledSendTime: string;
    selectDateTime: string;
    messageWillBeSent: string;
    confirmScheduledTime: string;
    confirmScheduledTimeHint: string;
    selectAutomationToEdit: string;
    selectAutomationDescription: string;
    configureAutomationDescription: string;
    currentScheduledTime: string;
    activateAutomation: string;
    automationActive: string;
    noTemplatesAvailable: string;
    completed: string;
    pending: string;
    confirmationTitle: string;
    stepsCompleted: string;
    updating: string;
    sending: string;
    updateConfirmation: string;
    sendConfirmation: string;
    completeAllQuestions: string;
    rsvpManagement: string;
    templates: string;
    sendRSVP: string;
    sendMessage: string;
    selectedGuests: string;
    selectTemplate: string;
    messagePreview: string;
    previewNote: string;
    bulkSendWarning: string;
    sendToGuests: string;
    noGuestsWithPhones: string;
    addPhoneNumbers: string;
    selectGuests: string;
    selectGuestsDescription: string;
    selectedGuestsCount: string;
    onlyGuestsWithPhones: string;
    sendRSVPDescription: string;
    addPhoneNumbersHint: string;
    dateSent: string;
    status: string;
    messagesLog: string;
    questions: string;
    personalWhatsappMessages: string;
    messageType: string;
    templateName: string;
    messageBody: string;
    variables: string;
    dateCreated: string;
    markMessagesAsSent: string;
    clickedSendButNotMarked: string;
    whichGuestsDidYouSendTo: string;
    pendingGuests: string;
    stayContinue: string;
    leaveWithoutSaving: string;
    markAllAsSentAndClose: string;
    // Send progress translations
    sendingMessages: string;
    messageSummary: string;
    recipients: string;
    sendingTo: string;
    messageResults: string;
    messageSent: string;
    messageFailed: string;
    messagesSent: string;
    messagesFailed: string;
    detailedResults: string;
    messageSentSuccessfully: string;
    messagesWillAppear: string;
    retryFailedMessages: string;
    pleaseWait: string;
    sendingSummary: string;
    messagesQueued: string;
    failedToSend: string;
    messageQueuedSingular: string;
    messagesQueuedPlural: string;
    // Send Automation types
    sendAutomations: string;
    createAutomation: string;
    runNow: string;
    automationName: string;
    scheduledTime: string;
    automationType: string;
    rsvpAutomation: string;
    reminderAutomation: string;
    rsvpAutomationDescription: string;
    reminderAutomationDescription: string;
    targetAudience: string;
    // Status translations
    statuses: {
      pending: string;
      inProgress: string;
      completed: string;
      failed: string;
    };
    guestsAttending: string;
    guestsNotAttending: string;
    allGuests: string;
    messages: string;
    attendingGuests: string;
    notAttendingGuests: string;
    noAutomationsTitle: string;
    noAutomationsDescription: string;
    createFirstAutomation: string;
    // Automation Info Dialog
    automationDetails: string;
    basicInformation: string;
    executionStatistics: string;
    totalMessagesSent: string;
    successfulMessages: string;
    failedMessages: string;
    completedAt: string;
    failureDetails: string;
    failureDetailsDescription: string;
    messageSid: string;
    errorCode: string;
    errorMessage: string;
    automationInProgressInfo: string;
    automationCompletedSuccessfully: string;
    automationFailedInfo: string;
    // Automation details components
    automationPending: string;
    automationPendingDescription: string;
    automationCompleted: string;
    automationCompletedDescription: string;
    automationFailed: string;
    automationFailedDescription: string;
    contactSupport: string;
    contactSupportDescription: string;
    contactSupportButton: string;
    messageSentTo: string;
    deactivateAutomation: string;
    viewFailureDetails: string;
    automationActiveMessage: string;
    // Preview dummy data
    preview: {
      weddingName: string;
      brideName: string;
      groomName: string;
      venueName: string;
      guestName: string;
      guestSide: string;
      guestRelation: string;
    };
    changeInvitationPhoto: string;
    addInvitationPhoto: string;
    changePhoto: string;
    addPhoto: string;
    removePhoto: string;
    presetQuestions: string;
    custom: string;
    createQuestionFormPlaceholder: string;
    addQuestionsFromSidebar: string;
    welcome: {
      title: string;
      subtitle: string;
      stepsTitle: string;
      step1Title: string;
      step1Description: string;
      step2Title: string;
      step2Description: string;
      getStarted: string;
      creating: string;
    };
    premiumPricing: {
      hero: {
        title: string;
        subtitle: string;
        description: string;
      };
      howItWorks: {
        title: string;
        step1: {
          title: string;
          description: string;
          icon: string;
        };
        step2: {
          title: string;
          description: string;
          icon: string;
        };
        step3: {
          title: string;
          description: string;
          icon: string;
        };
      };
      features: {
        title: string;
        rsvpMessages: {
          title: string;
          description: string;
          icon: string;
        };
        eventReminder: {
          title: string;
          description: string;
          icon: string;
        };
        giftLink?: {
          title: string;
          description: string;
          icon: string;
        };
        thankYou: {
          title: string;
          description: string;
          icon: string;
        };
        phoneSupport: {
          title: string;
          description: string;
          icon: string;
        };
        customDesign: {
          title: string;
          description: string;
          icon: string;
        };
        transportation: {
          title: string;
          description: string;
          icon: string;
        };
        mealPreferences: {
          title: string;
          description: string;
          icon: string;
        };
        customMessages: {
          title: string;
          description: string;
          icon: string;
        };
        smartTracking: {
          title: string;
          description: string;
          icon: string;
        };
      };
      pricing: {
        title: string;
        subtitle: string;
        startingPrice: string;
        perInvitee: string;
        calculator: {
          title: string;
          inputLabel: string;
          inputPlaceholder: string;
          priceLabel: string;
          totalPrice: string;
          perRecordRate: string;
          minRecords: string;
          examplesTitle: string;
          example1: string;
          example1Price: string;
          example1Rate: string;
          example2: string;
          example2Price: string;
          example2Rate: string;
        };
        customPricing: string;
      };
      testimonials: {
        title: string;
        testimonial1: {
          text: string;
          author: string;
          wedding: string;
        };
        testimonial2: {
          text: string;
          author: string;
          wedding: string;
        };
      };
      sampleMessage: {
        title: string;
        subtitle: string;
        messageText: string;
        variables: string;
      };
      cta: {
        title: string;
        description: string;
        upgradeButton: string;
        contactUs: string;
        guarantee: string;
      };
    };
  };
  automation: {
    allMessagesSent: string;
    successMessage: string;
    mostMessagesSent: string;
    partialSuccessMessage: string;
    issuesExplanation: string;
    sentOn: string;
    messagesBeingSent: string;
    inProgressMessage: string;
    somethingWentWrong: string;
    failedMessage: string;
    contactSupport: string;
    messageScheduled: string;
    willBeSentOn: string;
  };
  rsvpEmptyState: {
    title: string;
    description: string;
    createButton: string;
    creating: string;
  };
  rsvpQuestionManager: {
    title: string;
    description: string;
    questionBank: string;
    createCustom: string;
    saveForm: string;
    unsavedChanges: string;
    noQuestionsTitle: string;
    noQuestionsDescription: string;
    openQuestionBank: string;
    createCustomQuestion: string;
    predefinedQuestions: string;
    customQuestions: string;
    add: string;
    close: string;
    questionText: string;
    displayNameLabel: string;
    displayNameHelper: string;
    questionType: string;
    yesNoQuestion: string;
    multipleChoiceQuestion: string;
    answerOptions: string;
    addOption: string;
    cancel: string;
    createQuestion: string;
    displayNameAlert: string;
    questionTextHelper: string;
    yesNoType: string;
    multipleChoiceType: string;
    customLabel: string;
    requiredLabel: string;
    tableLabel: string;
    formSavedSuccess: string;
    formSaveError: string;
    questionsCount: string;
    bankDescription: string;
    booleanOptions: string;
    trueOptionLabel: string;
    falseOptionLabel: string;
    trueOptionHelper: string;
    falseOptionHelper: string;
  };
  rsvpQuestions: {
    attendance: {
      question: string;
      displayName: string;
    };
    sleepover: {
      question: string;
      displayName: string;
    };
    meal_preference: {
      question: string;
      displayName: string;
      options: {
        meat: string;
        fish: string;
        vegetarian: string;
        vegan: string;
      };
    };
    transportation: {
      question: string;
      displayName: string;
      options: {
        telAviv: string;
        jerusalem: string;
        haifa: string;
        none: string;
      };
    };
    dietary_restrictions: {
      question: string;
      displayName: string;
      options: {
        none: string;
        glutenFree: string;
        dairyFree: string;
        nutAllergy: string;
        other: string;
      };
    };
    amount: {
      question: string;
      displayName: string;
    };
  };
  rsvpStatusTab: {
    title: string;
    statistics: string;
    totalInvitations: string;
    submittedRSVP: string;
    attending: string;
    totalGuests: string;
    sleepover: string;
    transportation: string;
    rsvpList: string;
    name: string;
    phone: string;
    attendance: string;
    guestCount: string;
    sleepoverColumn: string;
    transportationColumn: string;
    status: string;
    pending: string;
    arriving: string;
    notArriving: string;
    draft: string;
    submitted: string;
    noData: string;
    loadingData: string;
    templatesSent: string;
    noTemplatesSent: string;
    sent: string;
    notSent: string;
    filterByTemplate: string;
    selectTemplates: string;
    selectTemplateFirst: string;
    invitationLink: string;
    copyInvitationLink: string;
    responseRate: string;
    responded: string;
    selectionBreakdown: string;
    failed: string;
    noTemplatesAvailable: string;
    unknownError: string;
    selectGuestsFirst: string;
  };
  thankYou: {
    thankYouTitle: string;
    rsvpSentSuccessfully: string;
    excitedToCelebrate: string;
    sorryYouCantAttend: string;
    thanksForLettingUsKnow: string;
    canUpdateAnytime: string;
    updateRsvp: string;
  };
  templates: {
    rawTemplate: string;
    uncategorized: string;
    noTemplate: string;
    selectThisTemplate: string;
    selectTemplate: string;
    messageTemplate: string;
    title: string;
    description: string;
    createDummy: string;
    creating: string;
    createSuccess: string;
    createError: string;
    createNew: string;
    createNewTemplate: string;
    templateName: string;
    templateNamePlaceholder: string;
    language: string;
    messageText: string;
    messageTextPlaceholder: string;
    availableVariables: string;
    clickToInsert: string;
    usedVariables: string;
    preview: string;
    createTemplate: string;
    noTemplates: string;
    loadError: string;
    unnamed: string;
    noContent: string;
    variables: string;
    name: string;
    type: string;
    category: string;
    eligibility: string;
    textType: string;
    mediaType: string;
    bothTypes: string;
    approved: string;
    pending: string;
    submitted: string;
    rejected: string;
    received: string;
    noVariables: string;
    templateInfo: string;
    messageContent: string;
    templateId: string;
    deleteTemplate: string;
    deleting: string;
    submitForApproval: string;
    submitting: string;
    approvalSuccess: string;
    approvalError: string;
    approvalStatus: string;
    approvalCategory: string;
    categoryUtility: string;
    categoryMarketing: string;
    categoryAuthentication: string;
    rejectionReason: string;
    checkApprovalStatus: string;
    whatsappApproval: string;
    submitForBusinessMessaging: string;
    selectCategoryDescription: string;
    whatHappensNext: string;
    templateSubmittedForReview: string;
    approvalTakesTime: string;
    trackStatusInDetails: string;
    onceApprovedUseForMessaging: string;
    templateSubmittedSuccessMessage: string;
    unknownError: string;
    whatsappStatus: string;
    approvedForBusinessMessaging: string;
    underReviewTime: string;
    receivedProcessingShortly: string;
    rejectedCheckReason: string;
    submitForWhatsappApprovalInfo: string;
    requestApproval: string;
    requestWhatsappApproval: string;
    checkingApprovalStatus: string;
  };
  globalTemplates: GlobalTemplatesTranslations;
  userRsvp: UserRSVPTranslations;
  rsvpSetup: RsvpSetupTranslations;
  seating: SeatingTranslations;
  payment: {
    success: {
      title: string;
      subtitle: string;
      description: string;
      featuresTitle: string;
      features: {
        customForm: string;
        unlimitedMessages: string;
        automation: string;
        analytics: string;
        support: string;
      };
      continueButton: string;
      loading: string;
    };
  };
  leads: {
    title: string;
    description: string;
    subtitle: string;
    columns: {
      name: string;
      email: string;
      phone: string;
      weddingDate: string;
      budget: string;
      quotation: string;
      advanceAmount: string;
      estimatedGuests: string;
      status: string;
      paymentStatus: string;
      source: string;
      service: string;
      followUp: string;
      actions: string;
      notes: string;
    };
    statuses: {
      new: string;
      initial_contact: string;
      contract_suggested: string;
      contract_signed: string;
      done: string;
      lost: string;
    };
    paymentStatuses: {
      awaiting_payment: string;
      advance_paid: string;
      paid_in_full: string;
    };
    sources: {
      website: string;
      referral: string;
      instagram: string;
      facebook: string;
      google: string;
      wedding_fair: string;
      direct: string;
      other: string;
    };
    stats: {
      totalLeads: string;
      newLeads: string;
      converted: string;
      conversionRate: string;
      expectedIncome: string;
      expectedIncomeTooltip: string;
    };
    activityPanel: {
      title: string;
      leadDetails: string;
      activityTimeline: string;
      addNote: string;
      addNotePlaceholder: string;
      noActivity: string;
      byUser: string;
    };
    events: {
      created: string;
      statusChanged: string;
      fieldUpdated: string;
      noteAdded: string;
      followUpSet: string;
      followUpCompleted: string;
    };
    form: {
      namePlaceholder: string;
      emailPlaceholder: string;
      phonePlaceholder: string;
      budgetPlaceholder: string;
      guestsPlaceholder: string;
      addLead: string;
      cancel: string;
      save: string;
      nameRequired: string;
      emailRequired: string;
      startTyping: string;
    };
    messages: {
      loadingLeads: string;
      noLeads: string;
      errorLoading: string;
      errorAddingNote: string;
      leadCreated: string;
      leadUpdated: string;
      leadDeleted: string;
      confirmDelete: string;
      followUpOverdue: string;
    };
    actions: {
      viewActivity: string;
    };
  };
  support: {
    title: string;
    description: string;
    nameLabel: string;
    emailLabel: string;
    subjectLabel: string;
    messageLabel: string;
    messagePlaceholder: string;
    sendButton: string;
    successMessage: string;
    errorMessage: string;
    fieldRequired: string;
    invalidEmail: string;
    subjectTooLong: string;
    messageTooShort: string;
    messageTooLong: string;
    buttonText: string;
  };
}

interface SeatingTranslations {
  title: string;
  description: string;
  setup: {
    title: string;
    addTable: string;
    editTable: string;
    deleteTable: string;
    tableNumber: string;
    tableName: string;
    tableNamePlaceholder: string;
    tableNameHelper: string;
    capacity: string;
    shape: string;
    notes: string;
    position: string;
    vipTable: string;
    shapes: {
      round: string;
      rectangular: string;
      square: string;
    };
    validation: {
      numberRequired: string;
      capacityRequired: string;
      capacityMinimum: string;
      shapeRequired: string;
    };
    deleteConfirm: string;
    deleteWithGuests: string;
  };
  layoutElements: {
    title: string;
    addElement: string;
    types: {
      stage: string;
      bar: string;
      foodCourt: string;
      danceFloor: string;
      entrance: string;
      bathroom: string;
      element: string;
    };
    properties: {
      type: string;
      size: string;
      position: string;
      customName: string;
      customNameHelper: string;
      shape: string;
    };
    shapes: {
      rectangle: string;
      circle: string;
    };
    deleteElement: string;
  };
  table: {
    defaultName: string;
  };
  tableProperties: {
    title: string;
  };
  bulkAdd: {
    title: string;
    quantity: string;
    quantityHelper: string;
    startingNumber: string;
    startingNumberHelper: string;
    capacityHelper: string;
    preview: string;
    create: string;
  };
  actions: {
    addTables: string;
    autoArrange: string;
    addGuest: string;
    assignGuests: string;
    attendanceTracker: string;
  };
  templates: Record<string, any>;
  assignment: {
    title: string;
    unassigned: string;
    assigned: string;
    autoAssign: string;
    dragHint: string;
    clickToAssign: string;
    removeGuest: string;
    moveGuest: string;
    tableCapacityReached: string;
    guestsRemaining: string;
    allAssigned: string;
    noMatchingGuests: string;
    noGuestsAssigned: string;
    filter: {
      title: string;
      all: string;
      byRelation: string;
      bySide: string;
      searchGuests: string;
    };
  };
  preview: {
    title: string;
    subtitle: string;
    export: string;
    print: string;
    zoomIn: string;
    zoomOut: string;
    resetView: string;
    viewMode: string;
    editMode: string;
  };
  stats: {
    totalGuests: string;
    assigned: string;
    unassigned: string;
    totalTables: string;
    averagePerTable: string;
    capacityUsed: string;
  };
  assignmentDialog: {
    title: string;
    autoAssign: string;
    clearAll: string;
    assigned: string;
    tables: string;
    capacity: string;
    unassigned: string;
    search: string;
    relation: string;
    side: string;
    all: string;
    selectAll: string;
    deselectAll: string;
    selectedCount: string;
    selectTable: string;
    assign: string;
    applyChanges: string;
    tablesAndAssignments: string;
    overCapacity: string;
    dropGuestsHere: string;
    noUnassignedGuests: string;
    confirmClearAll: string;
    confirmOverCapacity: string;
    applyFailed: string;
  };
  autoAssignment: {
    title: string;
    description: string;
    groupByRelation: string;
    groupBySide: string;
    preferFamilyTogether: string;
    run: string;
    confirm: string;
    success: string;
    noGuestsToAssign: string;
    noTablesAvailable: string;
    notEnoughCapacity: string;
    failed: string;
  };
  suggestions: {
    title: string;
    guestsToSitTogether: string;
    basedOnRelation: string;
    basedOnSide: string;
  };
  errors: {
    loadingTables: string;
    loadingGuests: string;
    creatingTable: string;
    updatingTable: string;
    deletingTable: string;
    assigningGuest: string;
    removingGuest: string;
  };
  attendance: {
    title: string;
    subtitle: string;
    stats: {
      confirmedGuests: string;
      checkedIn: string;
    };
    columns: {
      guestName: string;
      rsvpStatus: string;
      confirmedAmount: string;
      actualAmount: string;
      tableAssignment: string;
      checkInStatus: string;
    };
    rsvpStatus: {
      confirmed: string;
      declined: string;
      notAttending: string;
      notResponded: string;
    };
    checkIn: {
      checkedIn: string;
      notCheckedIn: string;
    };
    table: {
      notAssigned: string;
      tableNumber: string;
    };
    filters: {
      searchPlaceholder: string;
      showAll: string;
      showAllExplanation: string;
      copyLink: string;
      copied: string;
    };
  };
}

interface GlobalTemplatesTranslations {
  title: string;
  description: string;
  createNew: string;
  createTemplate: string;
  templateName: string;
  category: string;
  language: string;
  messageText: string;
  messagePreview: string;
  messageTextPlaceholder: string;
  variablesInfo: string;
  global: string;
  totalTemplates: string;
  noTemplates: string;
  noTemplatesInCategory: string;
  createSuccess: string;
  createError: string;
  loadError: string;
  created: string;
  categories: {
    initialRsvp: string;
    initialRsvpDescription: string;
    secondRsvp: string;
    secondRsvpDescription: string;
    finalRsvp: string;
    finalRsvpDescription: string;
    dayBefore: string;
    dayBeforeDescription: string;
    dayAfterThankyou: string;
    dayAfterThankyouDescription: string;
  };
}

interface RsvpSetupStepTranslations {
  title: string;
  description: string;
}

interface RsvpSetupTranslations {
  title: string;
  subtitle: string;
  loading: string;
  setupComplete: string;
  steps: {
    welcome: RsvpSetupStepTranslations;
    form: RsvpSetupStepTranslations;
    automations: RsvpSetupStepTranslations;
  };
}

interface UserRSVPTranslations {
  title: string;
  subtitle: string;
  launchRsvp: string;
  completeStepToContinue: string;
  steps: {
    createForm: string;
    createFormDesc: string;
    chooseMessages: string;
    chooseMessagesDesc: string;
    scheduleTimeline: string;
    scheduleTimelineDesc: string;
    reviewLaunch: string;
    reviewLaunchDesc: string;
  };
  form: {
    title: string;
    description: string;
    startWithDefaults: string;
    customizeQuestions: string;
    customizeDesc: string;
    availableQuestions: string;
    selectedCount: string;
    confirmQuestions: string;
    updateError: string;
    preview: string;
    addCustom: string;
    createCustomQuestion: string;
    questionText: string;
    displayName: string;
    displayNameHelp: string;
    questionType: string;
    selectOptions: string;
    option: string;
    addOption: string;
    quickStart: string;
    quickStartDesc: string;
    customize: string;
    createDefault: string;
    buildCustom: string;
    completed: string;
    completedDesc: string;
    customizeForm: string;
    createError: string;
    tip: string;
  };
  templates: {
    title: string;
    description: string;
    rsvpInitial: string;
    rsvpInitialDesc: string;
    dayBefore: string;
    dayBeforeDesc: string;
    thankYou: string;
    thankYouDesc: string;
    selectTemplate: string;
    template: string;
    preview: string;
    selected: string;
    selectionComplete: string;
    selectAllRequired: string;
    noTemplatesAvailable: string;
    previewTitle: string;
    previewPlaceholder: string;
  };
  scheduler: {
    title: string;
    description: string;
    scheduledTime: string;
    automationsCreated: string;
    completeAllSchedules: string;
    noTemplatesSelected: string;
    noScheduleItems: string;
    createAutomationsError: string;
    weddingDateRequired: string;
    templatesRequired: string;
    approvePlan: string;
    creatingAutomations: string;
    scheduleOverview: string;
    weddingDate: string;
    messageTimeline: string;
    onWeddingDay: string;
    oneDayBefore: string;
    oneDayAfter: string;
    daysBefore: string;
    daysAfter: string;
    existingAutomations: string;
  };
  review: {
    title: string;
    description: string;
    setupSummary: string;
    rsvpForm: string;
    rsvpFormDesc: string;
    messageTemplates: string;
    messageTemplatesDesc: string;
    automationSchedule: string;
    automationScheduleDesc: string;
    whatHappensNext: string;
    step1Title: string;
    step1Desc: string;
    step2Title: string;
    step2Desc: string;
    step3Title: string;
    step3Desc: string;
    launchRsvpSystem: string;
    completeAllSteps: string;
    launchSuccess: string;
  };
  dashboard: {
    title: string;
    subtitle: string;
    backToSetup: string;
    totalInvitees: string;
    guestsInvited: string;
    responseRate: string;
    responded: string;
    attending: string;
    confirmedAttending: string;
    automations: string;
    automationsComplete: string;
    responseProgress: string;
    responseProgressDesc: string;
    automationStatus: string;
    completed: string;
    inProgress: string;
    pending: string;
    automationStatusDesc: string;
    noAutomationsDesc: string;
    quickActions: string;
    viewInvitees: string;
    manageAutomations: string;
    editForm: string;
    helpText: string;
  };
  messagesPlan: {
    title: string;
    description: string;
    initialRsvp: {
      title: string;
      description: string;
    };
    secondRsvp: {
      title: string;
      description: string;
    };
    finalRsvp: {
      title: string;
      description: string;
    };
    dayBefore: {
      title: string;
      description: string;
    };
    dayAfterThankyou: {
      title: string;
      description: string;
    };
    selectTemplate: string;
    changeTemplate: string;
    templatesSelected: string;
    continue: string;
    loadingTemplates: string;
    noTemplatesAvailable: string;
    weddingTemplates: string;
    globalTemplates: string;
    weddingTemplate: string;
    globalTemplate: string;
  };
}
